apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-imagens-noticias
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-sessao-noticias
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi