apiVersion: v1
kind: Pod
metadata:
  name: volume-ed-pod
  labels:
    app: volume-ed
spec:
  containers:
    - name: volume-ed-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}