apiVersion: v1
kind: Pod
metadata:
  name: project-pod
spec:
  containers:
    - name: pod
      image: nginx:latest
      ports: 
        - containerPort: 3134
      resources:
      limits:
        memory: "128Mi"
        cpu: "500m"