apiVersion: v1
kind: Pod
metadata:
  name: pod-two
  labels:
    app: second-pod
spec:
  containers:
    - name: nginx-pod-two
      image: nginx:stable
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"