apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias-pod
      labels:
        app: portal-noticias
    spec: 
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-portal-noticias
  replicas: 3
  selector: 
    matchLabels:
      app: portal-noticias