apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias-pod
      labels:
        app: portal-noticias
    spec: 
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          resources:
            requests:
              cpu: 10m              
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-portal-noticias
          livenessProbe:
            httpGet:
              path: /
              port: 80 # escopo do container
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80 # escopo do container
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
  replicas: 3
  selector: 
    matchLabels:
      app: portal-noticias